/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        { type: 'autogenerated', dirName: 'Overview' }, // 按文件名排序
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Installation',
          items: [
            { type: 'autogenerated', dirName: 'Getting Started/Installation' }, // 按文件名排序
          ],
        },
        {
          type: 'category',
          label: 'Quick Start',
          items: [
            { type: 'autogenerated', dirName: 'Getting Started/Quick Start' }, // 按文件名排序
          ],
        },
        {
          type: 'category',
          label: 'Debugging Guide',
          items: [
            { type: 'autogenerated', dirName: 'Getting Started/Debugging Guide' }, // 按文件名排序
          ],
        },
        {
          type: 'category',
          label: 'FAQ',
          items: [
            { type: 'autogenerated', dirName: 'Getting Started/FAQ' }, // 按文件名排序
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'User Guides' }, // 按文件名排序
      ],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'Development' }, // 按文件名排序
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
