max_tokens_per_step: 128
max_actions_per_traj: 10

env_manager_cls: roll.pipeline.agentic.env_manager.traj_env_manager.TrajEnvManager
gem_qa:
  # RuleTaker Environments
  RuleTaker-d0:
    env_type: "logic:RuleTaker-d0"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d0-70k
  RuleTaker-d1:
    env_type: "logic:RuleTaker-d1"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d1-70k
  RuleTaker-d2:
    env_type: "logic:RuleTaker-d2"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d2-70k
  RuleTaker-d3:
    env_type: "logic:RuleTaker-d3"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d3-70k
  RuleTaker-d5:
    env_type: "logic:RuleTaker-d5"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/RuleTaker-d5-70k

  # QA Environments
  NaturalQuestions:
    env_type: "qa:NaturalQuestions"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: axon-rl/NaturalQuestions
  HotpotQA:
    env_type: "roll_qa"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/data/HotpotQA
      split: train
      question_key: problem
      answer_key: answer
  HotpotQA_with_mcp:
    env_type: "roll_qa"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    max_env_step_concurrent: 10
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/data/HotpotQA
      split: train
      question_key: problem
      answer_key: answer
    tool_wrapper:
      wrapper_args:
        tool_reward: 0.0
        tool_success_reward: 0.2
        max_tool_uses: 1
      tool_configs:
        - tool_id: mcp
          tool_args:
            server_url: xxx
  HotpotQA_with_search:
    env_type: "roll_qa"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    max_env_step_concurrent: 10
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/data/HotpotQA
      split: train
      question_key: problem
      answer_key: answer
    tool_wrapper:
      wrapper_args:
        tool_reward: 0.0
        tool_success_reward: 0.0
        max_tool_uses: 2
      tool_configs:
        - tool_id: xpeng_search
          tool_args:
            search_url: http://10.1.33.45:8000/retrieve
  Rlinf_search_r1:
    env_type: "roll_qa"
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    max_env_step_concurrent: 10
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/data/rlinf_searchr1_data/train_formatted_hf
      split: train
      question_key: question
      answer_key: answer
    tool_wrapper:
      wrapper_args:
        tool_reward: 0.0
        tool_success_reward: 0.0
        max_tool_uses: 2
      tool_configs:
        - tool_id: xpeng_search
          tool_args:
            search_url: http://10.1.33.45:8000/retrieve
  Rlinf_search_r1_val:
    env_type: roll_qa
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    max_env_step_concurrent: 10
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/data/rlinf_searchr1_data/val_formatted_hf
      split: val
      question_key: question
      answer_key: answer
    tool_wrapper:
      wrapper_args:
        tool_reward: 0.0
        tool_success_reward: 0.0
        max_tool_uses: 2
      tool_configs:
      - tool_id: xpeng_search
        tool_args:
          search_url: http://10.1.33.45:8000/retrieve
  nq_search_r1_train:
    env_type: roll_qa
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    max_env_step_concurrent: 10
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/code/Search-R1/data/nq_search/
      split: train
      question_key: question
      answer_key: golden_answers
    tool_wrapper:
      wrapper_args:
        tool_reward: 0.0
        tool_success_reward: 0.0
        max_tool_uses: 2
      tool_configs:
      - tool_id: xpeng_search
        tool_args:
          search_url: http://10.1.33.45:8000/retrieve
  musique_search_r1_val: # 数据格式目前有问题
    env_type: roll_qa
    max_steps: ${max_actions_per_traj}
    max_tokens_per_step: ${max_tokens_per_step}
    env_manager_cls: ${env_manager_cls}
    agent_system_template: ${qa_agent_system_template}
    agent_template: ${qa_agent_template}
    max_env_step_concurrent: 10
    env_config:
      dataset_name: /workspace/zhangjh37@xiaopeng.com/tmp/data/musique_hotpotqa_dataset
      split: test
      question_key: problem
      answer_key: answer
    tool_wrapper:
      wrapper_args:
        tool_reward: 0.0
        tool_success_reward: 0.0
        max_tool_uses: 2
      tool_configs:
      - tool_id: xpeng_search
        tool_args:
          search_url: http://10.1.33.45:8000/retrieve


qa_agent_system_template: You're a helpful assistant.
qa_agent_template: "{observation}"

